### ISSUE TITLE
1.8 compatibility

### ISSUE THREAD

**Issue by syabro** [bmihelac/django-import-export#200]
```
  File "/Users/syabro/.envs/homeowners/lib/python2.7/site-packages/import_export/resources.py", line 16, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related
```

because

>The django.db.models.related module has been removed and the Field.related attribute will be removed in Django 2.0.

https://docs.djangoproject.com/en/dev/releases/1.8/#model-field-related

**Comment by bmihelac** [comment]
Thanks for contributing. I did not check Django 1.8 yet. Would you like to write a patch for this? (please note that django 1.4.x should stay supported)

**Comment by syabro** [comment]
We'll upgrade our project to 1.8 when beta will be released around 15 Feb. If it'll be open still — will do.

**Comment by dericcrago** [comment]
I just ran into this too... Has any progress been made yet?

**Comment by 2xyo** [comment]
Django issue related to this issue:  https://code.djangoproject.com/ticket/21414

**Comment by 2xyo** [comment]
I started a fix 4ea278a61dd08ecf067d96ae2c4241539649d3db but  Django 1.8 causes other bugs : 

```
ERROR: test_related_one_to_one (core.tests.resources_tests.ModelResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoyo/projects/django-import-export/tests/core/tests/resources_tests.py", line 348, in test_related_one_to_one
    class EntryResource(resources.ModelResource):
  File "/home/yoyo/projects/django-import-export/tests/../import_export/resources.py", line 481, in __new__
    readonly=True)
  File "/home/yoyo/projects/django-import-export/tests/../import_export/resources.py", line 536, in field_from_django_field
    FieldWidget = self.widget_from_django_field(django_field)
  File "/home/yoyo/projects/django-import-export/tests/../import_export/resources.py", line 501, in widget_from_django_field
    internal_type = f.get_internal_type()
AttributeError: 'RelatedObject' object has no attribute 'get_internal_type'
```
See https://groups.google.com/forum/#!topic/django-developers/-zQL0skuPh0

**Comment by SalahAdDin** [comment]
I have the same error.

**Comment by bmihelac** [comment]
this should be fixed in master, report if it is not

**Comment by SalahAdDin** [comment]
I don't know if the pypi package is now updated, i had installed the github django-import-export branch.

**Comment by leosquared** [comment]
The pypi package is still not working with Django 1.8. Additionally it's giving me "No module named import-export" when it is included in the INSTALLED_APPS in settings.py.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by leosquared** [comment]
I don't know how to set this up through the github copy since the app is in heroku and everything they do needs to done through pip.

**Comment by bmihelac** [comment]
To install dev version:

    pip install -e git+https://github.com/bmihelac/django-import-export.git#egg=django-import-export

**Comment by michellemark** [comment]
This only works until I attempt to register the model and modeladmin classes with admin.site.register(MyModel, MyModelAdmin) then I get an error on this register line that states system_check_errors.extend(admin_class.check(model))
AttributeError: type object 'MyModelResource' has no attribute 'check'

**Comment by michellemark** [comment]
sorry that last error is what I get when I got desperate and attempted to register the Resource class instead... the actual error is: 

system_check_errors.extend(admin_class.check(model))
AttributeError: type object 'MyModelAdmin' has no attribute 'check'

**Comment by michellemark** [comment]
oh my goodness never mind, for anyone else who sees this the issue is simply that in addition to the ImportExportMixin your Admin class must also inherit from admin.ModelAdmin, despite that not being clear in the documentation

**Comment by leosquared** [comment]
Also I was able to pip install the github version which works with Django 1.8. Thanks @bmihelac !

**Comment by abcooley** [comment]
I was having issues with 1.8 as well with import/export but using the github rev latest works fine now.

**Comment by rcdosado** [comment]
issuing `python manage.py dumpdata admin` gives an error "No module named 'import_export', although its already in INSTALLED_APPS and i have an admin account created.

issuing `python manage.py dumpdata` works fine.

 im using python 2.7 and django 1.8

**Comment by khantthulinn** [comment]
Hi I read though above. Is this issue solved already? I still get No module named 'import_export' error when I put in INSTALLED_APPS.

**Comment by mikekeda** [comment]
same error, dev version also doesn't work
ImportError: No module named 'import_export'
Django==1.11
Python 3.4.3
